# Generated by Django 2.2.6 on 2019-10-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da validação')),
                ('field', models.CharField(max_length=140, verbose_name='Campo')),
                ('value', models.TextField(verbose_name='Valor')),
                ('message', models.TextField(verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Histórico de validação',
                'verbose_name_plural': 'Históricos de validação',
                'db_table': 'log_validador',
            },
        ),
    ]
