# Generated by Django 2.2.6 on 2019-10-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=140, verbose_name='Nome do campo')),
                ('validator', models.TextField(verbose_name='Validador')),
                ('message', models.TextField(verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Esquema de validação',
                'verbose_name_plural': 'Esquemas de validação',
                'db_table': 'schema_validador',
            },
        ),
    ]
